name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always

jobs: 
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all --check

      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-make
          components: clippy
      - name: Run Clippy
        run: cargo make lint

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            use-cross: false
            target: x86_64-unknown-linux-gnu
        #   - build: linux-aarch64
        #     os: ubuntu-latest
        #     use-cross: true
        #     target: aarch64-unknown-linux-gnu
          - build: macos
            os: macos-latest
            use-cross: false
            target: x86_64-apple-darwin
          - build: macos-aarch64
            os: macos-latest
            use-cross: false
            target: aarch64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install OpenSSL development libraries
        # if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y pkg-config libssl-dev
          else
            brew install openssl@3
          fi

      - name: Install cross
        if: matrix.use-cross
        uses: taiki-e/install-action@v2
        with:
         tool: cross

      - uses: moonrepo/setup-rust@v1
        with:
          targets: ${{ matrix.target }}

      - name: Build (without cross)
        if: "!matrix.use-cross"
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Build (cross)
        if: matrix.use-cross
        run: cross build --release --locked --target ${{ matrix.target }} 

